tuplas=("diego","souza","python")
print(tuplas)
print(tuplas[0])
print(tuplas[0:2])
print(len(tuplas))
print(tuplas+tuplas)
print(tuplas*5)
print("python" in tuplas)
lista=[1,4,"diego"]
tuplas2=tuple(lista)
print(tuplas2)
